### ISSUE TITLE
Upgrade Node-sass

### ISSUE THREAD

**Issue by akegan** [Exygy/sf-dahlia-pattern-library#94]
I just upgraded my computer to Mojave, and now when I try to run `npm run-script build` I get this error:
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/andreaegan/sf-dahlia-pattern-library/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/andreaegan/sf-dahlia-pattern-library/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/andreaegan/sf-dahlia-pattern-library/node_modules/gulp-sass/index.js:187:21)
```

This was using Node version 10.11.0 as I discovered worked for me in https://github.com/Exygy/sf-dahlia-pattern-library/pull/91

It looks like latest node-sass version is 4.12.0 ([release documentation](https://github.com/sass/node-sass/releases))

**Comment by callaghanc** [comment]
@slowbot i'll take an initial look at this and see if i can do the upgrade, will tag you for review

**Comment by bk3c** [comment]
I actually started moving this all forward for my own laptop (direct to node 12 seemed better at this point), and it turns out that to really get everything working right we'll need to upgrade gulp 3->4, which is non-trivial. I got about halfway through the work a couple weeks ago before other priorities took over, but I'm happy to get back to it at some point. In the meantime I'll see if I can organize my work enough to make a WIP branch so others can build on it if desired.

**Comment by callaghanc** [comment]
@bk3c ok, go ahead and put up a branch with your work so far
